version: '3'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: near_db
      POSTGRES_USER: near
      POSTGRES_PASSWORD: theendisnear
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: 'redis:latest'
    hostname: redis
    volumes:
      - redis_data:/data

  app:
    restart: unless-stopped
    build: .
    entrypoint: ["./wait-for-it.sh", "db:5432",
                 "--strict", "--"]
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      DEBUG: "True"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      POSTGRES_HOST: db
      POSTGRES_DB: near_db
      POSTGRES_USER: near
      POSTGRES_PASSWORD: theendisnear
      POSTGRES_PORT: 5432
    command: sh -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

  celery:
    restart: unless-stopped
    build: .
    entrypoint: ["./celery.sh"]
    environment:
      DEBUG: "True"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      POSTGRES_HOST: db
      POSTGRES_DB: near_db
      POSTGRES_USER: near
      POSTGRES_PASSWORD: theendisnear
      POSTGRES_PORT: 5432
    depends_on:
      - app
      - redis
      - db

volumes:
  db_data:
  redis_data: