# Generated by Django 5.0.3 on 2024-03-23 10:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(db_index=True, max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^\\d{5}$')])),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=5, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('description', models.TextField()),
                ('delivery_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_cargos', to='near_api_v1.location')),
                ('pick_up_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_up_cargos', to='near_api_v1.location')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{3}[A-Z]$')])),
                ('payload_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('current_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='near_api_v1.location')),
            ],
        ),
    ]
